%% This set of files contains the Matlab code for the comparison experiments 
%% in the following paper:
%
%  [1] L. He, J. Li, C. Liu and S. Li, 
%  Recent Advances on Spectral每Spatial Hyperspectral Image Classification: An Overview and New Guidelines. 
%  IEEE Transactions on Geoscience and Remote Sensing, vol. 56, no. 3, pp. 1579-1597, March 2018.
%
%% The Gabor features are generated by DLRGF:
%
%  [2] L. He, J. Li, A. Plaza and Y. Li,
%  Discriminative Low-Rank Gabor Filtering for Spectral每Spatial Hyperspectral Image Classification,
%  IEEE Transactions on Geoscience and Remote Sensing, vol. 55, no. 3, pp. 1381-1395, March 2017.
%
%% The EMAP features are built by:
%
%  [3] M. D. Mura, A. Villa, J. A. Benediktsson, J. Chanussot, and L. Bruzzone, 
%  Classification of hyperspectral images by using extended morphological attribute profiles and independent component analysis,
%  IEEE Geoscience and Remote Sensing Letters, vol. 8, no. 3, pp. 542每546, May 2011.
%
%% The Multinomial logistic regression (MLR) implimentation is by:
%
%  [4] J. Li, J. Bioucas-Dias and A. Plaza. 
%  Hyperspectral Image Segmentation Using a New Bayesian Approach with Active Learning, 
%  IEEE Transactions on Geoscience and Remote Sensing, vol. 49, no. 10, pp.3947-3960, October 2011.
%
%% the SVM implitation is by libSVM:
%
%  [5] Chih-Chung Chang and Chih-Jen Lin, 
%  LIBSVM : a library for support vector machines. 
%  ACM Transactions on Intelligent Systems and Technology, 2:27:1--27:27, 2011. 
%  Software available at http://www.csie.ntu.edu.tw/~cjlin/libsvm
%
%% The LBP is implemented by:
%
%  [6] J. Li, J. M. Bioucas-Dias and A. Plaza, 
%  Spectral每Spatial Classification of Hyperspectral Data Using Loopy Belief Propagation and Active Learning,
%  IEEE Transactions on Geoscience and Remote Sensing, vol. 51, no. 2, pp. 844-856, Feb. 2013.
%
%%
%%  If you use this demo, please cite these references 
%%  --- [1][2][3][4][5][6] ---
%%
%%  For their BibTeX formats, please see 
%%  --- Reference.bib ---
%%
%%  For their RIS formats, please see 
%%  --- Reference.enl ---
%%  
%%
%
%  Any suggestions and comments are appreciated, and please send them to
%  the authors: 
%  helin@scut.edu.cn; lijun48@mail.sysu.edu.cn; sysuliuchy@163.com